# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bpINIH0J0B3gMFr7d-hp4c2aAqZ5yJKA
"""

import tensorflow as tf
import tf_keras as tk
from PIL import Image, ImageOps
import numpy as np

# Load the model
model = tk.models.load_model("keras_model.h5", compile=False)

# Load labels
class_names = open("labels.txt", "r").readlines()

# Create array
data = np.ndarray(shape=(1, 224, 224, 3), dtype=np.float32)

# Open test image
image = Image.open("for test.jpg").convert("RGB")

# Resize image
size = (224, 224)
image = ImageOps.fit(image, size, Image.Resampling.LANCZOS)

# Convert to array
image_array = np.asarray(image)

# Normalize image
normalized_image_array = (image_array.astype(np.float32) / 127.5) - 1

# Load image
data[0] = normalized_image_array

# Predict
prediction = model.predict(data)

index = np.argmax(prediction)
class_name = class_names[index]
confidence_score = prediction[0][index]

print("Predicted Class:", class_name[2:].strip())
print("Confidence Score:", confidence_score)

import tensorflow as tf
import tf_keras as tk

print("TensorFlow:", tf.__version__)
print("TF-Keras:", tk.__version__)